[package]
name = "advent-of-code-2024"
version = "0.1.0"
edition = "2021"

[[bin]]
name = "io_utils"
test = false

[[bin]]
name = "template"
test = false

[dependencies]
good_lp = { version = "1.10.0", features = ["coin_cbc"], default-features = false }
microlp = "0.2.6"
regex = "1.11.1"
